spring:
  profiles:
    active:
      -dev
---              
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: microservicecloud-dept
 
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    instance-id: microservice-dept8001
    prefer-ip-address: true
info:
  app.name: yaorange-microservicecloud
  company.name: www.qiangge.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$   
---
server:
  port: 8001 
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
       #defaultZone: http://localhost:7001/eureka
       defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    instance-id: microservicecloud-dept8003
    prefer-ip-address: true     #访问路径可以显示IP地址  
info: 
  app.name: yaorange-microservicecloud
  company.name: www.qiangge.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$  
